version: '3.9'

services:
  backend:
    build:
      context: server/
    image: backend:1.0.0
    command: sh -c 'sleep 10 && npx sequelize-cli db:migrate && npm start'
    environment:
       DB__USER: simon
       DB_DB: note
       DB_PASSWORD: 123
       LOCALHOST: 3002
    ports:
      - 7001:3002
    depends_on:
      - postgres

  frontend:
    build:
      context: client/
    image: frontend:1.0.0
    ports: ["81:80"]
    environment:
      REACT_APP_HOST: http://backend:3002
     
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "note"
      POSTGRES_USER: "simon"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
